Repository the-events-calendar/tribe-common-styles, pull requests merged in 2019-11, with the labels that each got.

#56 add primary text light color
  variables/_colors.pcss
Labels: code review, merge

#58 update box shadow color
  variables/_box-shadows.pcss
  variables/_colors.pcss
Labels: code review, merge

#57 VR > Organizer Meta
  icons/link.svg
  icons/mail.svg
  icons/phone.svg
  variables/_svgs.pcss
Labels: merge

#59 VR > Venue meta
  icons/map-pin.svg
  variables/_svgs.pcss
Labels: code review
