Repository the-events-calendar/tribe-common-styles, pull requests merged in 2019-05, with the labels that each got.

#3 add box shadow for tooltip
  variables/_box-shadows.pcss
Labels: merge

#4 update styles for filter svg
  variables/_svgs.pcss
Labels: code review, merge

#5 add heading mixins
  mixins/_typography.pcss
Labels: code review

#6 add transition variables
  variables/_transitions.pcss
Labels: merge

#8 Fix/list view repairs
  variables/_grids.pcss
Labels: merge

#7 Include Required variables
  _all.pcss
  variables/_colors.pcss
  variables/_z-index.pcss
Labels: merge
