Repository the-events-calendar/tribe-common-styles, pull requests merged in 2019-10, with the labels that each got.

#49 VR > DQA Week view changes
  variables/_box-shadows.pcss
  variables/_colors.pcss
Labels: merge

#50 VR > Multiday Tooltip > Add new z-index.
  variables/_z-index.pcss
Labels: code review

#51 fix visibility mixins
  mixins/_visibility.pcss
Labels: code review

#52 VR > Messages > Add icon and colors.
  icons/messages-not-found.svg
  variables/_colors.pcss
  variables/_svgs.pcss
Labels: code review

#55 Feature/map view no venue
  icons/close.svg
  icons/no-map.svg
  variables/_svgs.pcss
Labels: code review, merge

#54 Recurring icons.
  variables/_svgs.pcss
Labels: merge
