Repository the-events-calendar/tribe-common-styles, pull requests merged in 2020-05, with the labels that each got.

#65 Update with current master
  icons/arrow.svg
  icons/error.svg
  icons/remove.svg
  mixins/_buttons.pcss
  variables/_colors.pcss
  variables/_svgs.pcss
Labels: code review

#66 Fix/virtual
  icons/arrow.svg
  icons/error.svg
  icons/remove.svg
  icons/virtual.svg
  mixins/_buttons.pcss
  variables/_colors.pcss
  variables/_svgs.pcss
Labels: code review

#64 Task/ve 18 virtual events label
  icons/virtual.svg
  mixins/_forms.pcss
  variables/_box-shadows.pcss
  variables/_colors.pcss
  variables/_forms.pcss
  variables/_svgs.pcss
Labels: merge

#67 Task/remove virtual icon
  icons/virtual.svg
  variables/_colors.pcss
  variables/_svgs.pcss
Labels: code review, merge
